name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U docker -d apisolid"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_USERNAME: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DATABASE: apisolid

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: |
          until pg_isready -h 127.0.0.1 -p 5432; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done
        env:
          PGUSER: docker
          PGPASSWORD: docker

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@127.0.0.1:5432/apisolid?schema=public"